export const ACTION = 'ACTION'

export const DRAW_CARD = 'DRAW_CARD'
export const DISCARD_CARD = 'DISCARD_CARD'
export const DEAL_CARDS = 'DEAL_CARDS'
export const NEW_GAME = 'NEW_GAME'
export const SET_NUM_PLAYERS = 'SET_NUM_PLAYERS'
export const SET_OLD_MAID = 'SET_OLD_MAID'
export const PASS_TURN = 'PASS_TURN'
export const WIN = 'WIN'
export const LOSE = 'LOSE'
